In [74]:
import pandas as pd
import numpy as np

In [75]:
#Import Bloomington,IN data into dataframe called "bloom"
bloom = pd.read_csv("../main_data/locale_specific_data/BloomingtonData.csv")
bloom.head()

,id,intakedate,intakereason,istransfer,sheltercode,identichipnumber,animalname,breedname,basecolour,speciesname,...,movementdate,movementtype,istrial,returndate,returnedreason,deceaseddate,deceasedreason,diedoffshelter,puttosleep,isdoa
0,15801,11/28/2009 12:00:00 AM,Moving,False,C09115463,0A115D7358,Jadzia,Domestic Short Hair,Tortoiseshell,Cat,...,05/13/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
1,15932,12/08/2009 12:00:00 AM,Moving,False,D09125594,0A11675477,Gonzo,German Shepherd Dog/Mix,Tan,Dog,...,04/24/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
2,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,04/15/2017 12:00:00 AM,Adoption,False,02/28/2020 12:00:00 AM,Stray,NaN,Died in care,False,False,False
3,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,02/29/2020 12:00:00 AM,Reclaimed,False,11/06/2023 12:00:00 AM,Stray,NaN,Died in care,False,False,False
4,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,12/17/2023 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False

In [76]:

#Remove duplicate rows
print("#rows before removing duplicates:",bloom.shape[0])
bloom1=bloom.drop_duplicates()
print("#rows after removing duplicates:",bloom1.shape[0])

#rows before removing duplicates: 34130
#rows after removing duplicates: 30839

In [77]:
#Restrict to dogs
bloomDogs = bloom1.loc[bloom1['speciesname'] == 'Dog']
bloomDogs.head(10)

,id,intakedate,intakereason,istransfer,sheltercode,identichipnumber,animalname,breedname,basecolour,speciesname,...,movementdate,movementtype,istrial,returndate,returnedreason,deceaseddate,deceasedreason,diedoffshelter,puttosleep,isdoa
1,15932,12/08/2009 12:00:00 AM,Moving,False,D09125594,0A11675477,Gonzo,German Shepherd Dog/Mix,Tan,Dog,...,04/24/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
2,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,04/15/2017 12:00:00 AM,Adoption,False,02/28/2020 12:00:00 AM,Stray,NaN,Died in care,False,False,False
3,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,02/29/2020 12:00:00 AM,Reclaimed,False,11/06/2023 12:00:00 AM,Stray,NaN,Died in care,False,False,False
4,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,12/17/2023 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
5,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,NaN,NaN,False,NaN,Stray,NaN,Died in care,False,False,False
9,31469,03/26/2013 12:00:00 AM,Incompatible with owner lifestyle,False,D1303720,981020007006095,Bonnie,Basenji/Mix,Brown and White,Dog,...,03/30/2013 12:00:00 AM,Adoption,False,05/08/2017 12:00:00 AM,Incompatible with owner lifestyle,NaN,Died in care,False,False,False
10,31469,03/26/2013 12:00:00 AM,Incompatible with owner lifestyle,False,D1303720,981020007006095,Bonnie,Basenji/Mix,Brown and White,Dog,...,05/09/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
13,46238,10/09/2016 12:00:00 AM,Abandoned,False,D16103207,981020019070093,Tennessee,Heeler/Mix,Brown and Black,Dog,...,11/26/2016 12:00:00 AM,Foster,False,07/23/2017 12:00:00 AM,Stray,NaN,Died in care,False,False,False
14,46238,10/09/2016 12:00:00 AM,Abandoned,False,D16103207,981020019070093,Tennessee,Heeler/Mix,Brown and Black,Dog,...,08/09/2017 12:00:00 AM,Foster,False,02/14/2018 12:00:00 AM,Stray,NaN,Died in care,False,False,False
15,46238,10/09/2016 12:00:00 AM,Abandoned,False,D16103207,981020019070093,Tennessee,Heeler/Mix,Brown and Black,Dog,...,02/14/2018 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False

In [78]:
import pandas as pd
import numpy as np

In [79]:
#Import Bloomington,IN data into dataframe called "bloom"
bloom = pd.read_csv("../main_data/locale_specific_data/BloomingtonData.csv")
bloom.head()

,id,intakedate,intakereason,istransfer,sheltercode,identichipnumber,animalname,breedname,basecolour,speciesname,...,movementdate,movementtype,istrial,returndate,returnedreason,deceaseddate,deceasedreason,diedoffshelter,puttosleep,isdoa
0,15801,11/28/2009 12:00:00 AM,Moving,False,C09115463,0A115D7358,Jadzia,Domestic Short Hair,Tortoiseshell,Cat,...,05/13/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
1,15932,12/08/2009 12:00:00 AM,Moving,False,D09125594,0A11675477,Gonzo,German Shepherd Dog/Mix,Tan,Dog,...,04/24/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
2,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,04/15/2017 12:00:00 AM,Adoption,False,02/28/2020 12:00:00 AM,Stray,NaN,Died in care,False,False,False
3,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,02/29/2020 12:00:00 AM,Reclaimed,False,11/06/2023 12:00:00 AM,Stray,NaN,Died in care,False,False,False
4,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,12/17/2023 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False

In [80]:
#Restrict to dogs
bloomDogs = bloom.loc[bloom['speciesname'] == 'Dog']
bloomDogs.head(10)

,id,intakedate,intakereason,istransfer,sheltercode,identichipnumber,animalname,breedname,basecolour,speciesname,...,movementdate,movementtype,istrial,returndate,returnedreason,deceaseddate,deceasedreason,diedoffshelter,puttosleep,isdoa
1,15932,12/08/2009 12:00:00 AM,Moving,False,D09125594,0A11675477,Gonzo,German Shepherd Dog/Mix,Tan,Dog,...,04/24/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
2,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,04/15/2017 12:00:00 AM,Adoption,False,02/28/2020 12:00:00 AM,Stray,NaN,Died in care,False,False,False
3,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,02/29/2020 12:00:00 AM,Reclaimed,False,11/06/2023 12:00:00 AM,Stray,NaN,Died in care,False,False,False
4,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,12/17/2023 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
5,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,NaN,NaN,False,NaN,Stray,NaN,Died in care,False,False,False
6,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,NaN,NaN,False,NaN,Stray,NaN,Died in care,False,False,False
9,31469,03/26/2013 12:00:00 AM,Incompatible with owner lifestyle,False,D1303720,981020007006095,Bonnie,Basenji/Mix,Brown and White,Dog,...,03/30/2013 12:00:00 AM,Adoption,False,05/08/2017 12:00:00 AM,Incompatible with owner lifestyle,NaN,Died in care,False,False,False
10,31469,03/26/2013 12:00:00 AM,Incompatible with owner lifestyle,False,D1303720,981020007006095,Bonnie,Basenji/Mix,Brown and White,Dog,...,05/09/2017 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
13,46238,10/09/2016 12:00:00 AM,Abandoned,False,D16103207,981020019070093,Tennessee,Heeler/Mix,Brown and Black,Dog,...,11/26/2016 12:00:00 AM,Foster,False,07/23/2017 12:00:00 AM,Stray,NaN,Died in care,False,False,False
14,46238,10/09/2016 12:00:00 AM,Abandoned,False,D16103207,981020019070093,Tennessee,Heeler/Mix,Brown and Black,Dog,...,08/09/2017 12:00:00 AM,Foster,False,02/14/2018 12:00:00 AM,Stray,NaN,Died in care,False,False,False

In [81]:
#checking for duplicate IDs
duplicate_rows = bloomDogs.duplicated(subset=['id'])
sum(duplicate_rows)

6550

In [82]:
bloomDogs["deceasedreason"].unique()

array(['Died in care', 'Healthy', 'Dead On Arrival',
       'UU - untreatable, unmanageable health', 'Biting',
       'Owner Requested', 'Temperament/Behavior', 'Court Order/ Legal',
       'UU-untreatable, unmanageable Behavior', 'Medical',
       'Vet advised euthanasia', 'TM - Treatable Manageable Behavior',
       'Died in community', 'TR-Treatable rehabilitable Behavior',
       'TM-Treatable Manageable Health'], dtype=object)

In [83]:
#Getting full list of original columns
cols = bloomDogs.columns
cols

Index(['id', 'intakedate', 'intakereason', 'istransfer', 'sheltercode',
       'identichipnumber', 'animalname', 'breedname', 'basecolour',
       'speciesname', 'animalage', 'sexname', 'location', 'movementdate',
       'movementtype', 'istrial', 'returndate', 'returnedreason',
       'deceaseddate', 'deceasedreason', 'diedoffshelter', 'puttosleep',
       'isdoa'],
      dtype='object')

In [84]:
#Looking at special case of repeated id
bloomcase = bloomDogs.loc[bloom['id'] == 28859]
bloomcase

,id,intakedate,intakereason,istransfer,sheltercode,identichipnumber,animalname,breedname,basecolour,speciesname,...,movementdate,movementtype,istrial,returndate,returnedreason,deceaseddate,deceasedreason,diedoffshelter,puttosleep,isdoa
2,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,04/15/2017 12:00:00 AM,Adoption,False,02/28/2020 12:00:00 AM,Stray,NaN,Died in care,False,False,False
3,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,02/29/2020 12:00:00 AM,Reclaimed,False,11/06/2023 12:00:00 AM,Stray,NaN,Died in care,False,False,False
4,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,12/17/2023 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
5,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,NaN,NaN,False,NaN,Stray,NaN,Died in care,False,False,False
6,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,NaN,NaN,False,NaN,Stray,NaN,Died in care,False,False,False

In [85]:
#Checking data types
bloomDogs.dtypes

id                   int64
intakedate          object
intakereason        object
istransfer            bool
sheltercode         object
identichipnumber    object
animalname          object
breedname           object
basecolour          object
speciesname         object
animalage           object
sexname             object
location            object
movementdate        object
movementtype        object
istrial               bool
returndate          object
returnedreason      object
deceaseddate        object
deceasedreason      object
diedoffshelter        bool
puttosleep            bool
isdoa                 bool
dtype: object

In [86]:
#Confirming lack of  spay/neuter information 
bloomDogs["sexname"].unique()

array(['Male', 'Female', 'Unknown'], dtype=object)

In [87]:
bloomDogs.loc[6]

id                                    28859
intakedate           08/10/2012 12:00:00 AM
intakereason                      Abandoned
istransfer                            False
sheltercode                       D23111515
identichipnumber                 0A13253C7B
animalname                           Maggie
breedname           Shep Mix/Siberian Husky
basecolour                    Black and Tan
speciesname                             Dog
animalage                11 years 9 months.
sexname                              Female
location                             Office
movementdate                            NaN
movementtype                            NaN
istrial                               False
returndate                              NaN
returnedreason                        Stray
deceaseddate                            NaN
deceasedreason                 Died in care
diedoffshelter                        False
puttosleep                            False
isdoa                                 False
Name: 6, dtype: object

In [88]:
sum(duplicate_rows)

6550

In [89]:
#Finding the ids with large number of repetitions
bloomDogs["id"].value_counts()

id
72299    42
74031    32
64999    27
72249    25
72513    23
         ..
63414     1
63411     1
63410     1
63402     1
79986     1
Name: count, Length: 6674, dtype: int64

In [90]:
#Finding the ids with large number of repetitions (all are with more than 15 occurences are shown)
bloomDogs[bloomDogs['id'].map(bloomDogs['id'].value_counts()) >15]["id"].value_counts()

id
72299    42
74031    32
64999    27
72249    25
72513    23
73703    21
77998    21
71109    21
72070    20
60639    20
73321    19
57223    19
73730    18
76032    18
72138    17
73335    17
63249    17
74447    17
74498    17
72415    16
Name: count, dtype: int64

In [91]:
bloomDogs["istransfer"].value_counts()

istransfer
False    13167
True        57
Name: count, dtype: int64

<div class="alert alert-block alert-warning">
Angela: Check this -- why 57 "istransfer" true vs 241 "transfer from other shelter" below.
</div>

In [92]:
bloomDogs["intakereason"].unique()

array(['Moving', 'Abandoned', 'Incompatible with owner lifestyle',
       'Rabies Monitoring', 'Marriage/Relationship split', 'Stray',
       'Police Assist', 'Biting', 'Unable to Afford',
       'Unsuitable Accommodation', 'Owner Deceased',
       'TNR - Trap/Neuter/Release', 'Transfer from Other Shelter',
       'Sick/Injured', 'Allergies', 'Landlord issues',
       'Litter relinquishment', 'Owner requested Euthanasia',
       'Born in Shelter', 'Abuse/ neglect',
       'Incompatible with other pets', 'Behavioral Issues',
       'Return Adopt - Behavior', 'Return adopt - lifestyle issue',
       'Return Adopt - Animal Health'], dtype=object)

In [93]:
bloomDogs["intakereason"].value_counts()

intakereason
Stray                                6533
Incompatible with owner lifestyle    1535
Litter relinquishment                 733
Unsuitable Accommodation              632
Police Assist                         563
Moving                                489
Abandoned                             399
Unable to Afford                      347
Landlord issues                       287
Abuse/ neglect                        254
Transfer from Other Shelter           241
Owner Deceased                        196
Born in Shelter                       173
Incompatible with other pets          142
Rabies Monitoring                     134
Sick/Injured                          133
Biting                                117
Marriage/Relationship split           114
TNR - Trap/Neuter/Release              53
Allergies                              53
Behavioral Issues                      39
Owner requested Euthanasia             31
Return Adopt - Behavior                13
Return adopt - lifestyle issue         12
Return Adopt - Animal Health            1
Name: count, dtype: int64

In [94]:
bloomDogs["movementtype"].unique()

array(['Adoption', 'Reclaimed', nan, 'Foster', 'Transfer', 'Stolen',
       'Escaped'], dtype=object)

In [95]:
bloomDogs["movementtype"].value_counts()

movementtype
Adoption     5363
Reclaimed    2814
Foster       1765
Transfer      140
Escaped         5
Stolen          2
Name: count, dtype: int64

In [96]:
bloomDogs["returnedreason"].value_counts()

returnedreason
Stray                                11909
Incompatible with owner lifestyle      355
Return adopt - lifestyle issue         202
Return Adopt - Behavior                171
Biting                                  65
Incompatible with other pets            63
Police Assist                           52
Moving                                  50
Unsuitable Accommodation                50
Return Adopt - Other                    45
Landlord issues                         41
Owner requested Euthanasia              41
Rabies Monitoring                       33
Behavioral Issues                       25
Unable to Afford                        25
Transfer from Other Shelter             19
Abandoned                               18
DOA                                     17
Owner Deceased                          12
Allergies                                9
Litter relinquishment                    7
Sick/Injured                             6
Marriage/Relationship split              4
Abuse/ neglect                           3
Return Adopt - Animal Health             2
Name: count, dtype: int64

In [97]:
bloomDogs["deceasedreason"].value_counts()

deceasedreason
Court Order/ Legal                       12529
Died in care                               283
UU-untreatable, unmanageable Behavior      157
UU - untreatable, unmanageable health       91
Owner Requested                             52
Dead On Arrival                             39
TM - Treatable Manageable Behavior          28
Biting                                      16
Temperament/Behavior                        11
TR-Treatable rehabilitable Behavior          7
Vet advised euthanasia                       4
Medical                                      2
Died in community                            2
TM-Treatable Manageable Health               2
Healthy                                      1
Name: count, dtype: int64

In [98]:
#checking for duplicate IDs - dog IDs with more than one entry
duplicate_dogs = bloomDogs.duplicated(subset=['id'])
sum(duplicate_dogs)

6550

In [99]:
bloomDogs["deceasedreason"].unique()

array(['Died in care', 'Healthy', 'Dead On Arrival',
       'UU - untreatable, unmanageable health', 'Biting',
       'Owner Requested', 'Temperament/Behavior', 'Court Order/ Legal',
       'UU-untreatable, unmanageable Behavior', 'Medical',
       'Vet advised euthanasia', 'TM - Treatable Manageable Behavior',
       'Died in community', 'TR-Treatable rehabilitable Behavior',
       'TM-Treatable Manageable Health'], dtype=object)

In [100]:
#Getting full list of original columns
cols = bloomDogs.columns
cols

Index(['id', 'intakedate', 'intakereason', 'istransfer', 'sheltercode',
       'identichipnumber', 'animalname', 'breedname', 'basecolour',
       'speciesname', 'animalage', 'sexname', 'location', 'movementdate',
       'movementtype', 'istrial', 'returndate', 'returnedreason',
       'deceaseddate', 'deceasedreason', 'diedoffshelter', 'puttosleep',
       'isdoa'],
      dtype='object')

In [101]:
#Looking at special case of repeated id
bloomcase = bloomDogs.loc[bloom['id'] == 28859]
bloomcase

,id,intakedate,intakereason,istransfer,sheltercode,identichipnumber,animalname,breedname,basecolour,speciesname,...,movementdate,movementtype,istrial,returndate,returnedreason,deceaseddate,deceasedreason,diedoffshelter,puttosleep,isdoa
2,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,04/15/2017 12:00:00 AM,Adoption,False,02/28/2020 12:00:00 AM,Stray,NaN,Died in care,False,False,False
3,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,02/29/2020 12:00:00 AM,Reclaimed,False,11/06/2023 12:00:00 AM,Stray,NaN,Died in care,False,False,False
4,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,12/17/2023 12:00:00 AM,Adoption,False,NaN,Stray,NaN,Died in care,False,False,False
5,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,NaN,NaN,False,NaN,Stray,NaN,Died in care,False,False,False
6,28859,08/10/2012 12:00:00 AM,Abandoned,False,D23111515,0A13253C7B,Maggie,Shep Mix/Siberian Husky,Black and Tan,Dog,...,NaN,NaN,False,NaN,Stray,NaN,Died in care,False,False,False

In [102]:
#Checking data types
bloomDogs.dtypes

id                   int64
intakedate          object
intakereason        object
istransfer            bool
sheltercode         object
identichipnumber    object
animalname          object
breedname           object
basecolour          object
speciesname         object
animalage           object
sexname             object
location            object
movementdate        object
movementtype        object
istrial               bool
returndate          object
returnedreason      object
deceaseddate        object
deceasedreason      object
diedoffshelter        bool
puttosleep            bool
isdoa                 bool
dtype: object

In [103]:
#Confirming lack of  spay/neuter information 
bloomDogs["sexname"].unique()
bloomDogs.loc[6]

id                                    28859
intakedate           08/10/2012 12:00:00 AM
intakereason                      Abandoned
istransfer                            False
sheltercode                       D23111515
identichipnumber                 0A13253C7B
animalname                           Maggie
breedname           Shep Mix/Siberian Husky
basecolour                    Black and Tan
speciesname                             Dog
animalage                11 years 9 months.
sexname                              Female
location                             Office
movementdate                            NaN
movementtype                            NaN
istrial                               False
returndate                              NaN
returnedreason                        Stray
deceaseddate                            NaN
deceasedreason                 Died in care
diedoffshelter                        False
puttosleep                            False
isdoa                                 False
Name: 6, dtype: object

In [104]:
#Total number of duplicate rows
sum(duplicate_rows)

6550

In [105]:
#Finding the ids with large number of repetitions
bloomDogs["id"].value_counts()

id
72299    42
74031    32
64999    27
72249    25
72513    23
         ..
63414     1
63411     1
63410     1
63402     1
79986     1
Name: count, Length: 6674, dtype: int64

In [106]:
#Finding the ids with large number of repetitions (all are with more than 15 occurences are shown)
bloomDogs[bloomDogs['id'].map(bloomDogs['id'].value_counts()) >15]["id"].value_counts()
bloomDogs["istransfer"].value_counts()

istransfer
False    13167
True        57
Name: count, dtype: int64

Angela: Check this -- why 57 "istransfer" true vs 241 "transfer from other shelter" below.

Answer:  probably due to duplicate portions of rows

In [107]:
bloomDogs["intakereason"].unique()

array(['Moving', 'Abandoned', 'Incompatible with owner lifestyle',
       'Rabies Monitoring', 'Marriage/Relationship split', 'Stray',
       'Police Assist', 'Biting', 'Unable to Afford',
       'Unsuitable Accommodation', 'Owner Deceased',
       'TNR - Trap/Neuter/Release', 'Transfer from Other Shelter',
       'Sick/Injured', 'Allergies', 'Landlord issues',
       'Litter relinquishment', 'Owner requested Euthanasia',
       'Born in Shelter', 'Abuse/ neglect',
       'Incompatible with other pets', 'Behavioral Issues',
       'Return Adopt - Behavior', 'Return adopt - lifestyle issue',
       'Return Adopt - Animal Health'], dtype=object)

In [108]:
bloomDogs["intakereason"].value_counts()

intakereason
Stray                                6533
Incompatible with owner lifestyle    1535
Litter relinquishment                 733
Unsuitable Accommodation              632
Police Assist                         563
Moving                                489
Abandoned                             399
Unable to Afford                      347
Landlord issues                       287
Abuse/ neglect                        254
Transfer from Other Shelter           241
Owner Deceased                        196
Born in Shelter                       173
Incompatible with other pets          142
Rabies Monitoring                     134
Sick/Injured                          133
Biting                                117
Marriage/Relationship split           114
TNR - Trap/Neuter/Release              53
Allergies                              53
Behavioral Issues                      39
Owner requested Euthanasia             31
Return Adopt - Behavior                13
Return adopt - lifestyle issue         12
Return Adopt - Animal Health            1
Name: count, dtype: int64

In [109]:
bloomDogs["movementtype"].unique()

array(['Adoption', 'Reclaimed', nan, 'Foster', 'Transfer', 'Stolen',
       'Escaped'], dtype=object)

In [110]:
bloomDogs["movementtype"].value_counts()

movementtype
Adoption     5363
Reclaimed    2814
Foster       1765
Transfer      140
Escaped         5
Stolen          2
Name: count, dtype: int64

In [111]:
bloomDogs["returnedreason"].value_counts()

returnedreason
Stray                                11909
Incompatible with owner lifestyle      355
Return adopt - lifestyle issue         202
Return Adopt - Behavior                171
Biting                                  65
Incompatible with other pets            63
Police Assist                           52
Moving                                  50
Unsuitable Accommodation                50
Return Adopt - Other                    45
Landlord issues                         41
Owner requested Euthanasia              41
Rabies Monitoring                       33
Behavioral Issues                       25
Unable to Afford                        25
Transfer from Other Shelter             19
Abandoned                               18
DOA                                     17
Owner Deceased                          12
Allergies                                9
Litter relinquishment                    7
Sick/Injured                             6
Marriage/Relationship split              4
Abuse/ neglect                           3
Return Adopt - Animal Health             2
Name: count, dtype: int64

In [112]:
bloomDogs["deceasedreason"].value_counts()

deceasedreason
Court Order/ Legal                       12529
Died in care                               283
UU-untreatable, unmanageable Behavior      157
UU - untreatable, unmanageable health       91
Owner Requested                             52
Dead On Arrival                             39
TM - Treatable Manageable Behavior          28
Biting                                      16
Temperament/Behavior                        11
TR-Treatable rehabilitable Behavior          7
Vet advised euthanasia                       4
Medical                                      2
Died in community                            2
TM-Treatable Manageable Health               2
Healthy                                      1
Name: count, dtype: int64

In [113]:
bloomDogs.count()

id                  13224
intakedate          13224
intakereason        13224
istransfer          13224
sheltercode         13224
identichipnumber    11888
animalname          13224
breedname           13223
basecolour          13224
speciesname         13224
animalage           13224
sexname             13224
location            13224
movementdate        10089
movementtype        10089
istrial             13224
returndate           3613
returnedreason      13224
deceaseddate          462
deceasedreason      13224
diedoffshelter      13224
puttosleep          13224
isdoa               13224
dtype: int64